config/routes.rb
Rails.application.routes.draw do
  root "countries#index"
  resources :countries
  resources :regions
  resources :cities
  resources :camps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camp.rb
class Camp < ApplicationRecord

  validates :name, { presence: true,
                     uniqueness: true,
                     format: { with: /\A[a-zA-Z0-9а-яА-Я'\s-]+\z/,
                               message: "only allows letters"
                     }
  }
  validates :price, { numericality: { greater_than: 0,
                                      allow_nil: true
                      }
  }
  validates_presence_of :name, :price
  belongs_to :city

end

app/models/city.rb
class City < ApplicationRecord

  validates :name, { presence: true,
                     uniqueness: true,
                     format: { with: /\A[a-zA-Z0-9а-яА-Я'\s-]+\z/,
                               message: "only allows letters"
                     }
  }

  belongs_to :region
  has_many   :camps,
             :dependent => :destroy

end

app/models/country.rb
class Country < ApplicationRecord

  validates :name, { presence: true,
                     uniqueness: true,
                     format: { with: /\A[a-zA-Z0-9а-яА-Я'\s-]+\z/,
                               message: "only allows letters"
                     }
  }

  has_many :regions,
           :dependent => :destroy

end

app/models/region.rb
class Region < ApplicationRecord

  validates :name, { presence: true,
                     uniqueness: true,
                     format: { with: /\A[0-9a-zA-Z0-9а-яА-Я'\s-]+\z/,
                               message: "only allows letters"
                     }
  }

  belongs_to :country
  has_many   :cities,
             :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def render_404
    render file: "public/404.html", status: 404
  end

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController

  before_action :find_camp, only: [:show, :edit, :update, :destroy]

  def index
    @camp = Camp
    @camp = @camp.includes(city: [ region: :country ]).order("city_id, id")
    @camp = @camp.where("city_id = ?", params[:id])       if params[:id]
  end

  def show
  end

  def create
    @camp = Camp.create(params[:camp].permit!)
    if @camp.errors.empty?
      flash[:success] = "Турбаза успешно добавлена!"
      redirect_to camp_path(@camp)
    else
      flash.now[:error] = "Такая турбаза уже есть!!!"
      render action: "new"
    end
  end

  def new
    @camp = Camp.new
  end

  def edit
  end

  def update
    @camp.update_attributes(params[:camp].permit!)
    if @camp.errors.empty?
      flash[:success] = "Турбаза успешно обновлена!"
      redirect_to camp_path(@camp)
    else
      flash.now[:error] = "Такая турбаза уже есть!!!"
      render action: "edit"
    end
  end

  def destroy
    @camp.destroy
    redirect_to action: "index"
  end

  private

  def find_camp
    @camp = Camp.where(id: params[:id]).first
    render_404 unless @camp
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  before_action :find_city, only: [:show, :edit, :update, :destroy]

  def index
    @city = City
    @city = @city.includes(:region => :country).order("region_id, id")
    @city = @city.where("region_id = ?", params[:id])       if params[:id]
  end

  def show
  end

  def create
    @city = City.create(params[:city].permit!)
    if @city.errors.empty?
      flash[:success] = "Город успешно добавлен!"
      redirect_to city_path(@city)
    else
      flash.now[:error] = "Такой город уже есть!!!"
      render "new"
    end
  end

  def new
    @city = City.new
  end

  def edit
  end

  def update
    @city.update_attributes(params[:city].permit!)
    if @city.errors.empty?
      flash[:success] = "Город успешно обновлен!"
      redirect_to city_path(@city)
    else
      flash.now[:error] = "Такой город уже есть!!!"
      render "edit"
    end
  end

  def destroy
    @city.destroy
    redirect_to action: "index"
  end

  private

  def find_city
    @city = City.where(id: params[:id]).first
    render_404 unless @city
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @country = Country
    @country = @country.order("id")
  end

  def show
  end

  def create
    @country = Country.create(params[:country].permit!)
    if @country.errors.empty?
      flash[:success] = "Страна успешно добавлена!"
      redirect_to country_path(@country)
    else
      flash.now[:error] = "Такая страна уже есть!!!"
      render "new"
    end
  end

  def new
    @country = Country.new
  end

  def edit
  end

  def update
    @country.update_attributes(params[:country].permit!)
    if @country.errors.empty?
      flash[:success] = "Страна успешно обновлена!"
      redirect_to country_path(@country)
    else
      render "edit"
    end
  end

  def destroy
    @country.destroy
    redirect_to action: "index"
  end

  private

  def find_item
    @country = Country.where(id: params[:id]).first
    render_404 unless @country
  end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  before_action :find_region, only: [:show, :edit, :update, :destroy]

  def index
    @region = Region
    @region = @region.includes(:country).order("country_id, id")
    @region = @region.where("country_id = ?", params[:id])       if params[:id]
  end

  def show
  end

  def create
    @region = Region.create(params[:region].permit!)
    if @region.errors.empty?
      flash[:success] = "Регион успешно добавлен!"
      redirect_to region_path(@region)
    else
      flash.now[:error] = "Такой регион уже есть!!!"
      render "new"
    end
  end

  def new
    @region = Region.new
  end

  def edit
  end

  def update
    @region.update_attributes(params[:region].permit!)
    if @region.errors.empty?
      flash[:success] = "Регион успешно обновлен!"
      redirect_to region_path(@region)
    else
      flash.now[:error] = "Такой регион уже есть!!!"
      render "edit"
    end
  end

  def destroy
    @region.destroy
    redirect_to action: "index"
  end

  private

  def find_region
    @region = Region.where(id: params[:id]).first
    render_404 unless @region
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/camps/_form.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :city_id, "Выберите город:" %> <br/>
      <%= f.grouped_collection_select(:city_id, Region.all, :cities, :name, :id, :name) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :name, "Название турбазы:" %>
      <%= f.text_field :name, title: "Допустимы русские и латинские символы, тире, апостроф, пробел", placeholder: " ",
                              class: "form-control", required: true, pattern: "[A-Za-zА-Яа-я' -]+" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :description, "Описание турбазы:" %>
      <%= f.text_area :description, title: "Напишите описание", class: "form-control" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :price, "Цена, руб./сутки:" %>
      <%= f.text_field :price, title: "Напишите цену проживания в сутки в целочисленном формате", placeholder: " ",
                               class: "form-control", required: true, pattern: "[1-9][0-9]*" %>
    </div>
  </div>
</div>

    <%= f.submit "Сохранить", class: "btn btn-outline-success btn-sm" %>

app/views/camps/edit.html.erb
<div class="row mt-2">
  <h3>Редактирование турбазы</h3>
</div>

<%= form_with model: @camp do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/camps/index.html.erb
<div class="row">
  <h2>Турбазы</h2>
</div>
<% if @camp.empty? %>
  <div class="row">
    <b>Турбаз пока нет</b>
  </div>
<% else %>
  <div class="row">
    <table class="table table-sm table-hover table-responsive">
      <thead>
      <tr>
        <th>Турбаза</th>
        <th>Город</th>
        <th>Регион</th>
        <th>Страна</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @camp.each do |i| %>
        <tr data-path="<%= camp_path(i) %>">
          <td><%= link_to i.name, camp_path(i) %></td>
          <td><%= link_to i.city.name, camps_path(:id => i.city_id) %></td>
          <td><%= link_to i.city.region.name, cities_path(:id => i.city.region_id) %></td>
          <td><%= link_to i.city.region.country.name, regions_path(:id => i.city.region.country_id) %></td>
          <td><%= link_to "изменить", edit_camp_path(i), class: "btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to "удалить", camp_path(i), method: :delete, data: { confirm: "Точно удалить?" },
                          class: "btn btn-outline-danger btn-sm" %>
          </td>
      </tr>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<div class="row">
  <%= link_to "Добавить турбазу", new_camp_path(), class: "btn btn-outline-primary btn-sm mb-lg-3 mb-xs-2" %>
</div>

app/views/camps/new.html.erb
<div class="row mt-2">
  <h3>Добавление новой турбазы</h3>
</div>

<%= form_with model: @camp do |f| %>

<%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/camps/show.html.erb
<div class="row">
  <h2><%= @camp.name %></h2>
</div>
<div class="row">
  <p>
    <%= @camp.city.region.country.name %>,
    <%= @camp.city.region.name %>,
    <%= @camp.city.name %>
  </p>
  <br/><br/><br/>
</div>

<div class="row">
  <p><b>Описание:</b></p>
  <p><%= @camp.description %></p>
</div>

<div class="row">
  <p><b>Цена: </b></p>
  <p><%= @camp.price %> руб./сутки</p>
</div>

app/views/cities/_form.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="form-group">
      <%= f.label :region_id, "Выберите регион:" %> <br/>
      <%= f.grouped_collection_select(:region_id, Country.all, :regions, :name, :id, :name) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-3">
    <div class="form-group">
      <%= f.label :name, "Название города:" %>
      <%= f.text_field :name, title: "Допустимы русские и латинские символы, тире, апостроф, пробел", placeholder: " ",
                              class: "form-control", required: true, pattern: "[A-Za-zА-Яа-я' -]+" %>
    </div>
  </div>
</div>

    <%= f.submit "Сохранить", class: "btn btn-outline-success btn-sm" %>

app/views/cities/edit.html.erb
<div class="row mt-2">
  <h3>Редактирование города</h3>
</div>

<%= form_with model: @city do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/cities/index.html.erb
<div class="row">
  <h2>Города</h2>
</div>
<% if @city.empty? %>
  <div class="row">
    <b>Городов пока нет</b>
  </div>
<% else %>
  <div class="row">
    <table class="table table-sm table-hover table-responsive">
      <thead>
      <tr>
        <th>Город</th>
        <th>Регион</th>
        <th>Страна</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @city.each do |i| %>
      <tr data-path="<%= city_path(i) %>">
        <td><%= link_to i.name, camps_path(:id => i.id) %></td>
        <td><%= link_to i.region.name, cities_path(:id => i.region_id) %></td>
        <td><%= link_to i.region.country.name, regions_path(:id => i.region.country_id) %></td>
        <td><%= link_to "изменить", edit_city_path(i), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to "удалить", city_path(i), method: :delete, data: { confirm: "Точно удалить?" },
                        class: "btn btn-outline-danger btn-sm" %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<div class="row">
  <%= link_to "Добавить город", new_city_path(), class: "btn btn-outline-primary btn-sm mb-lg-3 mb-xs-2" %>
</div>

app/views/cities/new.html.erb
<div class="row mt-2">
  <h3>Добавление новго города</h3>
</div>

<%= form_with model: @city do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/cities/show.html.erb
<div class="row">
  <h2><%= @city.name %></h2>
</div>
<div class="row">
  <p>
    <%= @city.region.country.name %>,
    <%= @city.region.name %>
  </p>
</div>

app/views/countries/_form.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="form-group">
      <%= f.label :name, "Название страны:" %>
      <%= f.text_field :name, title: "Допустимы русские и латинские символы, тире, апостроф, пробел", class: "form-control",
                              placeholder: " ", required: true, pattern: "[A-Za-zА-Яа-я' -]+" %>
    </div>
   </div>
</div>

    <%= f.submit "Сохранить", class: "btn btn-outline-success btn-sm" %>

app/views/countries/edit.html.erb
<div class="row mt-2">
  <h3>Редактирование страны</h3>
</div>

<%= form_with model: @country do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/countries/index.html.erb
<div class="row">
  <h2>Страны</h2>
</div>
<% if @country.empty? %>
  <div class="row">
    <b>Стран пока нет</b>
  </div>
<% else %>
<div class="row">
  <table class="table table-sm table-hover table-responsive">
    <% @country.each do |i| %>
    <tr data-path="<%= country_path(i) %>">
      <td><%= link_to i.name, regions_path(:id => i.id) %></td>
      <td><%= link_to "изменить", edit_country_path(i), class: "btn btn-outline-secondary btn-sm" %></td>
      <td><%= link_to "удалить", country_path(i), method: :delete, data: { confirm: "Точно удалить?" },
                                                  class: "btn btn-outline-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<% end %>

<div class="row">
  <%= link_to "Добавить страну", new_country_path(), class: "btn btn-outline-primary btn-sm mb-lg-3 mb-xs-2" %>
</div>

app/views/countries/new.html.erb
<div class="row mt-2">
  <h3>Добавление новой страны</h3>
</div>

<%= form_with model: @country do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/countries/show.html.erb
<div class="row">
  <h2><%= @country.name %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectMirturbaz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark sticky-top">
      <div class="container">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Страны", countries_path(), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Регионы", regions_path(), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Города", cities_path(), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Турбазы", camps_path(), class: "nav-link" %>
            </li>
          </ul>
        </div>
    </nav>

    <div class="container">
      <p style="color: red;"><%= flash[:error] %></p>
      <p style="color: green;"><%= flash[:success] %></p>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/regions/_form.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="form-group">
      <%= f.label :country_id, "Выберите страну:" %> <br/>
      <%= f.collection_select :country_id, Country.all, :id, :name, class: "form-control" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-3">
    <div class="form-group">
      <%= f.label :name, "Название региона:" %>
      <%= f.text_field :name, title: "Допустимы русские и латинские символы, тире, апостроф, пробел", placeholder: " ",
                              class: "form-control", required: true, pattern: "[A-Za-zА-Яа-я' -]+" %>
    </div>
  </div>
</div>

    <%= f.submit "Сохранить", class: "btn btn-outline-success btn-sm" %>

app/views/regions/edit.html.erb
<div class="row mt-2">
  <h3>Редактирование региона</h3>
</div>
<%= form_with model: @region do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/regions/index.html.erb
<div class="row">
  <h2>Регионы</h2>
</div>
<% if @region.empty? %>
  <div class="row">
    <b>Регионов пока нет</b>
  </div>
<% else %>
<div class="row">
  <table class="table table-sm table-hover table-responsive">
    <thead>
    <tr>
      <th>Регион</th>
      <th>Страна</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <% @region.each do |i| %>
      <tr data-path="<%= region_path(i) %>">
        <td><%= link_to i.name, cities_path(:id => i.id) %></td>
        <td><%= link_to i.country.name, regions_path(:id => i.country_id) %></td>
        <td><%= link_to "Изменить", edit_region_path(i), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to "удалить", region_path(i), method: :delete, data: { confirm: "Точно удалить?" },
                        class: "btn btn-outline-danger btn-sm" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

<div class="row">
  <%= link_to "Добавить регион", new_region_path(), class: "btn btn-outline-primary btn-sm mb-lg-3 mb-xs-2" %>
</div>

app/views/regions/new.html.erb
<div class="row mt-2">
  <h3>Добавление нового региона</h3>
</div>

<%= form_with model: @region do |f| %>

  <%= render partial: "form", locals: { f: f } %>

<% end %>

app/views/regions/show.html.erb
<div class="row">
  <h2><%= @region.name %></h2>
</div>
<div class="row">
  <p>
    <%= @region.country.name %>
  </p>
</div>